[bell]
animation = "EaseOutExpo"
color = "#800000"
duration = 0

[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#dcdfe4"
yellow = "#e5c07b"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
background = "#282c34"
foreground = "#dcdfe4"

[colors.hints.end]
background = "#282c34"
foreground = "#e5c07b"

[colors.hints.start]
background = "#e5c07b"
foreground = "#282c34"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#dcdfe4"
yellow = "#e5c07b"

[colors.primary]
background = "#282c34"
foreground = "#dcdfe4"

[colors.search.focused_match]
background = "#e5c07b"
foreground = "#282c34"

[colors.search.matches]
background = "#98c379"
foreground = "#282c34"

[colors.selection]
background = "#282c34"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
blink_interval = 750
blink_timeout = 5
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"
style = { blinking = "Off", shape = "Block" }

[font]
size = 16.0
normal = { family = "FiraMono Nerd Font", style = "Medium" }
bold = { family = "FiraMono Nerd Font", style = "Bold" }
italic = { family = "FiraMono Nerd Font", style = "Italic" }
bold_italic = { family = "FiraMono Nerd Font", style = "Bold Italic" }
offset = { x = 0, y = 0 }

[keyboard]
bindings = [
  { key = "N", mods = "Control", action = "CreateNewWindow" }
]

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"
title = "Alacritty"
padding = { x = 10, y = 10}

[general]
live_config_reload = true
